#!/bin/bash

SYNCROOT=~/.sync

# cd to the repository
cd $SYNCROOT

if [ -n "`hg st`" ]; then
    echo "WARNING: uncommitted changes in $SYNCROOT" >&2

    if [ ! -t 0 ]; then
        echo "ERROR: will not run unattended with uncommitted changes; dying" >&2
        exit 1
    fi
fi

git fetch git@git.quadco.net:sync

if [ -x $SYNCROOT/sync-run ]; then
    $SYNCROOT/sync-run
else
    echo "sync-run is not executable"
    exit 1
fi
