# if the agent is being forwarded (and not running on the local host), allow
# all sessions to also use this agent instance
if [ -n "$SSH_AUTH_SOCK" -a -z "`ps aux | grep ssh-agent | grep -v grep`" ]; then
    ~/bin/reagent add $SSH_AUTH_SOCK

    # keep the actual agent socket path so it can be cleaned up properly upon
    # this session's termination
    export SSH_AUTH_SOCK_ORIG="$SSH_AUTH_SOCK"
fi

if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi
